fix: add condition to validate if element "variable" exists
eduNEXT/tutor-contrib-edunext-distro pull request #44
Opened 2023-04-14 21:49 UTC by luisfelipec95

# Description

This PR fixes  the following error:  If a package is added without variables this will raise the following error
![190263652-8c1c3d90-b952-4e7d-80ea-8a96d631264d](https://user-images.githubusercontent.com/78836902/232159402-5b4be3eb-3b0d-44c0-bd82-b60cf53f64a1.png)

# How to test

-  enabling distro plugin

`pip install git+https://github.com/eduNEXT/tutor-contrib-edunext-distro.git@DS-481`
`tutor plugins enable distro`

-  remove package variables: tutor-contrib-edunext-distro/tutordistro/plugin.py

Example:
`"EOX_THEMING_DPKG": {
            "index": "git",
            "name": "eox-theming",
            "repo": "eox-theming",
            "version": "v5.0.0",
            "domain": "github.com",
            "protocol": "https",
            "path": "eduNEXT",
            "EOX_THEMING_CONFIG_SOURCES":[
                "from_eox_tenant_microsite_v2",
                "from_django_settings"
            ],
            "private": False,
        },`

-  saving the config changes

`tutor config save`

2023-04-18 19:35 UTC, JuanDavidBuitrago submitted a review, later dismissed
It looks good to me. It is working!!

2023-04-18 19:42 UTC, dcoa commented
Looks good, I just wondering if could be the case that I define just one type of variable, for example, production variables but not dev variables.

2023-04-18 20:42 UTC, JuanDavidBuitrago commented
> 

It's possible, but it works also if you use a variable, I tested this case too.

2023-04-19 13:44 UTC, luisfelipec95 commented
@dcoa do you have another comment?

2023-04-19 20:14 UTC, dcoa requested changes
I tested it and I realized 3 things:
- There is a typo that makes any variable charged in the environment. 
- I test the use case of my question and fail. 
Define dev variables but not production:
![image](https://user-images.githubusercontent.com/66016493/233187991-e31a710d-ccde-4df1-994b-e730b6966e3b.png)

I left a comment explaining how we can change the line to support that case.

- Can we delete the empty definitions in plugin.py?

2023-04-19 21:35 UTC, JuanDavidBuitrago commented
> I tested it and I realized 3 things:
> 
>     * There is a typo that makes any variable charged in the environment.
Thanks @dcoa, I had not noticed this error 
> 
>     * I test the use case of my question and fail.
I test changing the typo mistake and fail as you say
>       Define dev variables but not production:
>       ![image](https://user-images.githubusercontent.com/66016493/233187991-e31a710d-ccde-4df1-994b-e730b6966e3b.png)
> 
> 
> I left a comment explaining how we can change the line to support that case.
> 
>     * Can we delete the empty definitions in plugin.py?
I think it is a good idea to use this PR to delete the empty definitions, could you do this? @luisfelipec95

2023-04-20 22:58 UTC, dcoa commented
@ hi, @luisfelipec95 please don't forget to update `plugin.py` as well.

2023-04-21 04:54 UTC, MaferMazu commented
@luisfelipec95, @dcoa proposes to edit the plugin.py file to delete the empty variables, for example, this https://github.com/eduNEXT/tutor-contrib-edunext-distro/blob/master/tutordistro/plugin.py#L82. I think it is a good idea. Can you do it? The rest looks good to me :D

2023-04-21 05:40 UTC, luisfelipec95 commented
> @luisfelipec95, @dcoa proposes to edit the plugin.py file to delete the empty variables, for example, this https://github.com/eduNEXT/tutor-contrib-edunext-distro/blob/master/tutordistro/plugin.py#L82. I think it is a good idea. Can you do it? The rest looks good to me :D

Done, thanks

2023-04-21 06:01 UTC, dcoa approved these changes

2023-04-21 08:39 UTC, JuanDavidBuitrago approved these changes
Thanks, @luisfelipec95

2023-04-21 13:44 UTC, merged